[package]
name = "const_struct_derive"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
description.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.106"
quote = "1.0.45"
syn = {version = "2.0.117", features = ["full", "extra-traits"]}
convert_case = "0.11.0"
crc = "3.4.0"
rand = { version = "0.10.1", optional = true }

[features]
rand_support = ["rand"]

[package.metadata.release]
tag = false
