[package]
name = "test_gen_code"
authors.workspace = true
version.workspace = true
edition.workspace = true
description.workspace = true
publish = false

[package.metadata.release]
release = false

[dependencies]
const_struct_derive.workspace = true
paste = "1.0"
